### PR TITLE
Allow subdirectories in scripts directory

### PR DESCRIPTION
**Pull request by dmazuruk**
Hi,

it would be nice to be able to place scripts in subdirectories and grouping them however we like. In our current project we have around 700 scripts and counting. I really dislike navigating through this directory in my IDE.
I let myself to provide an implementation of this feature and I've prepared a pull request.
What do you think of such feature? Is there any reason this change shouldn't be provided?

Regards,
Dawid

### CODE REVIEW

**Comment by harawata** [comment]
This is another possible use case of a custom FileMigrationLoader (which is not implemented yet).
Please give me some time to think about it!

**Comment by dmazuruk** [comment]
Yes, custom FileMigrationLoader would also do the job.
Let me know if you decide something or if I can help you somehow.
Thanks.

**Comment by harawata** [comment]
Hi @dmazuruk ,

The mentioned change is now available in the latest 3.3.2-SNAPSHOT.
I copied the relevant part of this PR and made an example.
https://github.com/harawata/custom-file-migration-loader

Please see #107 for the details about the enhancement.
Feedback is welcome!

**Comment by harawata** [comment]
I'll close this PR in favor of #107 .

**Comment by dmazuruk** [comment]
Hi @harawata,

sorry for late response, I have finally found time to work on that topic.
I have just tested `custom-file-migration-loader` and there is one crucial, in my case, problem, it won't work for already existing scripts. It recognizes all scripts as `...pending...`. My proposal worked fine even when I moved existing scripts to new directories.
What do you think about it? How could I solve the issue with `CustomFileMigrationLoader`?

Thank you,
Dawid

**Comment by harawata** [comment]
Hi @dmazuruk ,

I rewrote the class from scratch.
Could you try the new version, please?

**Comment by dmazuruk** [comment]
Hi @harawata,

it works now, thank you, I will do some more testing.
Now I need to convince my team to use SNAPSHOT ;)
Are you going to release anytime soon?

Thanks, 
Dawid

**Comment by harawata** [comment]
Thanks for the feedback, @dmazuruk !
Still waiting for a pending work in the core. I'm sorry for the long wait.
As there has been some enhancements in 3.3.2, it would be appreciated if you could try SNAPSHOT to make sure there is no regression.

**Pull request closed without merging**
