### PR TITLE
Improve `status` command with `missing` migrations

### PR DESCRIPTION
**Pull request by ffissore**
The status command compares the list of local migrations with those found on db. This may lead to misleading output when two or more developers are working on the same db but from different git branches: a migration which is applied but locally missing won't be shown by the status command.

This PR introduces "missing" migrations. The changelog is merged with the list of local migrations, and changelog entries which are not part of the list of local migrations are shown as "...missing...". Example output

```
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20190620071710 2019-06-20 09:41:51 create changelog
20190620071711 2019-06-20 09:41:51 first migration
20190620074320    ...missing...    migration1
20190620085416 2019-06-20 10:54:19 migration2
```

Here someone has applied "migration1" which is missing from our local branch.

### CODE REVIEW

**Comment by harawata** [comment]
Hi @ffissore ,

Thanks for the PR!
I agree that the current output is not great, so +1 for the improvement.

In the proposed output, though, the 'missing' migration is actually applied to the database, so omitting the timestamp could be confusing in a different way, IMHO.

How about reusing the [`DatabaseOperation.checkSkippedOrMissing()`](https://github.com/mybatis/migrations/blob/mybatis-migrations-3.3.5/src/main/java/org/apache/ibatis/migration/operations/DatabaseOperation.java) method added in #125 ?

So, there will be a WARNING after the list of migrations. e.g.

```
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20190620071710 2019-06-20 09:41:51 create changelog
20190620071711 2019-06-20 09:41:51 first migration
20190620074320 2019-06-20 09:46:12 migration1
20190620085416 2019-06-20 10:54:19 migration2

WARNING: Missing migration script. id='20190620074320', description='migration1'.
```

Printing the warning is pretty easy.

```java
if (changelog != null) {
  checkSkippedOrMissing(changelog, migrations, printStream);
}
```

Plus, we don't need to modify `Change` for this enhancement (I prefer it that way).
If highlighting the missing migration in the list is important, adding a subclass of `Change` to the list would do the job.

```java
class MissingScript extends Change {
  MissingScript(BigDecimal id, String appliedTimestamp, String description) {
    super(id, appliedTimestamp, description);
  }

  @Override
  public String toString() {
    return getId() + " " + getAppliedTimestamp() + " "
        + getDescription() + " <=== MISSING!";
  }
}
```

The output would be...

```
ID             Applied At          Description
================================================================================
20190620071710 2019-06-20 09:41:51 create changelog
20190620071711 2019-06-20 09:41:51 first migration
20190620074320 2019-06-20 09:46:12 migration1 <=== MISSING!
20190620085416 2019-06-20 10:54:19 migration2

WARNING: Missing migration script. id='20190620074320', description='migration1'.
```

**Comment by ffissore** [comment]
Thank you @harawata I've addressed your feedback. Output is now

```
ID             Applied At          Description
================================================================================
20190620071710 2019-06-21 09:02:01 create changelog
20190620071711 2019-06-21 09:02:01 first migration
20190620074320 2019-06-21 09:02:01 migration1 <=== MISSING!
20190620085416 2019-06-21 09:02:01 migration2

WARNING: Missing migration script. id='20190620074320', description='migration1'.
```

**Comment by harawata** [comment]
Thank you, @ffissore !

**Comment by ffissore** [comment]
Thank you for caring about community contributions, @harawata!

**Pull request merged**
