### PR TITLE
Combined pull requests (status, BOM handling, sequential ordering, version conflict detection, etc)

### PR DESCRIPTION
**Pull request by Mazrick**
I wanted all of the features available in the pull requests:
* mybatis/migrations#27
* mybatis/migrations#16

So, I started from the most current master, and merged those pulls into this branch.

I also:
* fixed a BOM issue
  * saving a script in windows with UTF-8 characters, fails to migrate when a BOM is inserted
* Fixed/added version conflict detection
* Added change filename validation configuration option
* Added sequence number padding configuration option for filenames

I have fully tested locally with updated unit tests.

*There were some dependency changes made to the pom.xml on some of the pull requests, which I am not fully informed about, so if there are any pieces which should first be reverted or changed, please feel free to comment and enlighten me!*

### CODE REVIEW

**Comment by hazendaz** [comment]
@Mazrick Can you rebase and squash your commits?

**Comment by harawata** [comment]
@Mazrick , Thank you for your contribution!
But combining multiple PRs does not seem to be a good idea to me.

Please use the GitHub's [reaction feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to up/down vote the PRs instead.
This is very important for us to decide which PR to merge. :-)

**Comment by Mazrick** [comment]
@harawata I tend to agree with you, but we are forced to do things we don't really like to when the maintainer lag is literally Mar 9, 2015 - Apr, 9, 2016.
I'll consider going through the work of re-basing and re-contributing all of the PRs separately.

**Comment by hazendaz** [comment]
We are trying to improve our support so lagging goes away.  If you can get us something it will see a release very soon.


Sent from Outlook Mobile






On Thu, Apr 21, 2016 at 9:25 AM -0700, "Crispin Botticelli" <notifications@github.com> wrote:





@harawata I tend to agree with you, but we are forced to do things we don't really like to when the maintainer lag is literally Mar 9, 2015 - Apr, 9, 2016.
I'll consider going through the work of re-basing and re-contributing all of the PRs separately.

---

**Comment by harawata** [comment]
Thank you for your understanding and contribution, @Mazrick !

We have already merged #29 and implemented #16 (in a different way. see #14).
Feedback for these changes are also welcome :-)

Regards,
Iwao

**Comment by emacarron** [comment]
@Mazrick considering how much you have paid for the tool I suppose you can imagine that we work here in our spare time and just for fun so I am also sorry for the lag but this is how ths works.

**Comment by Mazrick** [comment]
@emacarron, I totally appreciate the effort you guys have put into this tool! It does a lot of what I needed in a very straight forward way!
I only paid weeks of time vs. the months of effort evident in this solution! I'm not trying to complain about the lag, just point out in response to @harawata 's comment that I was forced into combining the PRs myself locally, which I didn't want to do. I was simply boxed into a corner at the time.

At this point development has diverged a bit, as evidenced by the fact that some of the fixes and merges are built upon each other, and some of the code was merged into the base and some of my changes are not. So I'm thinking about separating them into staged pull requests that build on each other. I'll endeavor to submit only one PR at a time, then only after it is accepted, I'll submit the next, if the it builds on the first.

Thank You!

**Pull request closed without merging**
