### PR TITLE
Fix info command by using a mybatis-migrations.properties file

### PR DESCRIPTION
**Pull request by xshyamx**
The `info` command is currently reading from the `pom.properties` file which does not contain the keys that it is looking for so, the output is
```
null 3.3.10 (null)
```
<details>
<summary>Full info output</summary>

```
------------------------------------------------------------------------
-- MyBatis Migrations - info
------------------------------------------------------------------------
null 3.3.10 (null)
Java version: 1.8.0_302, vendor: Oracle Corporation
Java home: /home/shyam/.sdkman/candidates/java/8.0.302-open/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: "5.18.5-200.fc36.x86_64", arch: "amd64", family: "unix"
------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Fri Jun 24 20:41:08 IST 2022
-- Final Memory: 5M/479M
------------------------------------------------------------------------
```

</details>

This pull request tries to fix it by using a filtered properties file to read these properties from which is fixed at build time. The new output looks as follows

```
MyBatis Migrations 3.3.11-SNAPSHOT (1.8.0_302)
```

<details>
<summary>Full output</summary>

```
------------------------------------------------------------------------
-- MyBatis Migrations - info
------------------------------------------------------------------------
MyBatis Migrations 3.3.11-SNAPSHOT (1.8.0_302)
Java version: 1.8.0_302, vendor: Oracle Corporation
Java home: /home/shyam/.sdkman/candidates/java/8.0.302-open/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "Linux", version: "5.18.5-200.fc36.x86_64", arch: "amd64", family: "unix"
------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Fri Jun 24 20:54:32 IST 2022
-- Final Memory: 28M/220M
------------------------------------------------------------------------
```

</details>

### CODE REVIEW

**Comment by hazendaz** [comment]
For reference, the existing 3.3.10 release contains this meta data

```
artifactId=mybatis-migrations
groupId=org.mybatis
version=3.3.10
```

**Comment by hazendaz** [comment]
@xshyamx Can you look at the locale data?  Its coming out as 'Default locale: en_null' on ubuntu.  Other than that I'm good with this and confirmed it is a defect.  Its been an issue for at least 6 years and prior to that the build data was a problem even longer.  I suspect the project had its own pom properties at some point as there is filtering around that in really old versions.

Anyway how to fix, your test fails due to the 'null' in the locale data.  That is on github actions now that I patched that test to output content ont the failure.  I wouldn't expect you to solve why ubuntu may not have that variable but at least check around and see if its the correct field for use there and likely add a patch so it doesn't echo null if not present.

**Comment by xshyamx** [comment]
The ubuntu-latest does not have the system property `user.country` set which shows up as null. So, instead of relying on system properties have used the default locale & charset objects.

**Comment by hazendaz** [comment]
@xshyamx Thank you!  Code is merged to master now.

**Comment by xshyamx** [comment]
Thank you @hazendaz

**Pull request merged**
