### PR TITLE
UpScript command

### PR DESCRIPTION
**Pull request by jollyblade**
Hi, 

I guess this feature would be quite interesting for many people, please review, and share your thoughts.

What it does:
- prints all pending changes including changelog updates as a textfile
- db admins can review the script before executing it on a productive system
- no version parameters are needed, like for the script command
- unit test added

Best regards,
Marton

### CODE REVIEW

**Comment by jollyblade** [comment]
Hi, 

Could you please review my pull request, and give a short update on the topic? :) 

Best,
Marton

**Comment by Mazrick** [comment]
The Travis tests were failing for the unit test you created "NewCommandTest". It was not able to resolve the test folder when running on the Travis test machine.
I have fixed this as part of #28

**Comment by jollyblade** [comment]
Hi, the unit tests run through by me, what are those travis tests mentioned? How can I try them?
Cheers! Otherwise we're using the feature already.

**Comment by jollyblade** [comment]
Okay, I checked the output logs, the build failed because of an unresolved parent pom version. I fixed that issues, and pulled my changes, because I needed to fix that for my local build too, I had to do a rebase because of the master changes.

**Comment by hazendaz** [comment]
@jollyblade Can you rebase against the current master so it flushes out all the commits already on master and then squash the commits?

git pull --rebase origin master

**Comment by jollyblade** [comment]
Hi Jeremy,

Of course i will do it when i get back to my laptop ;)

Best regards,
Marton

Az iPhone-omról küldve

2016. ápr. 9. dátummal, 18:42 időpontban Jeremy Landis <notifications@github.com> írta:

**Comment by jollyblade** [comment]
Hi Jeremy, 

Done. 

Best regards

**Comment by harawata** [comment]
This feature is implemented as #29 .
Hope that meets your requirement, too.
Thank you for your contribution, @jollyblade !

**Comment by jollyblade** [comment]
Hi, 

I think so, however we are already doing productive deployments with my version, so we will need to change to the official version later on. Thanks anyway!

Cheers, 
Marton

**Pull request closed without merging**
