### PR TITLE
adding instructions for sdkman

### PR DESCRIPTION
**Pull request by xshyamx**
MyBatis Migrations is available as a candidate from [SDKMAN](https://sdkman.io/sdks#mybtais) which provides an easy alternative to install MyBatis Migrations

### CODE REVIEW

**Review by h3adache — CHANGES_REQUESTED** [review]
Interesting that they just have it as MyBatis. Wonder if they could rename it to MyBatisMigrations instead. I think this is ok to add but I'm a little worried that we don't maintain this directly and issues with it opened with us won't be actionable. wdty @harawata?

**Comment by harawata** [comment]
Yeah...I usually avoid adding links to external stuff for the reason @h3adache mentioned.
How about wait and see if this gets many upvotes?

I also agree with @h3adache about the package name.
"MyBatis" usually means the [core part](https://github.com/mybatis/mybatis-3/).

**Comment by xshyamx** [comment]
I understand your concern about the name but, in the context of SDKMAN `mybatis` is concise and specific. The tool listing provides a more comprehensive description of the tool which looks like the following

```
--------------------------------------------------------------------------------
MyBatis Migrations (3.3.10)                      https://mybatis.org/migrations/

The MyBatis Schema Migration System (or MyBatis Migrations for short) seeks to
provide database migrations for any database (new or existing) and make the
current status of the database easily accessible and comprehensible. Installing
this candidate provides the migrate command for managing database migrations

                                                           $ sdk install mybatis
--------------------------------------------------------------------------------
```

**Comment by h3adache** [comment]
I wouldn't be opposed to adding an 'alternative methods of installation section' that clearly explains that these aren't maintained by us and just points to sdkman.

Node.js has an example of this https://nodejs.org/en/download/package-manager/

Not sure if it's worth doing for now. @harawata ?

**Comment by harawata** [comment]
@h3adache ,

I have no strong opinion about this.
If there is a problem (the package is not updated frequently, etc.), we can revert.

**Comment by h3adache** [comment]
How about this under the docker section then @xshyamx?

Package Manager
---
**Note:** These are not maintained by the MyBatis team and issues should be reported to the package maintainers.
* [SDKMAN](https://sdkman.io/sdks#mybatis) - `sdk install mybatis`

**Pull request closed without merging**
