### PR TITLE
Adding the ability to have migration scripts reference an outside fil…

### PR DESCRIPTION
**Pull request by shadowane**
…e in order to better support diffs and version tracking in things like packages and procedures.

Currently it is a huge headache to maintain packages because there is no way to compare between different migration files. Each time a package needs to be updated, a new migration file must be created and so version control gets lost. It's also can be unwieldy updating the code because the same set of code exists in the undo section which shouldn't be changed. This request adds in the ability to use @FILE: to reference a file in the newly added ./file directory. It also contains an update to the new command which will populate the migration script for the user if given filetemplate reference.

Limitation: This does have an issue though. Because the migration script is referencing an outside file, new updates to the outside file will cause all existing migration scripts referencing it to change. The undo section will still have the full rollback, but it's not possible to just roll forward from the beginning of the migrations for this type. However, usage of this is completely optional and I feel the benefits greatly outweigh this limitation.

### CODE REVIEW

**Comment by harawata** [comment]
Hi @shadowane ,
Thank you for the PR!

As you mentioned in the "Limitation" part, the idea seems to contradict the philosophy of Migration.
You should probably create a separate file that contains the latest package definition somewhere outside of Migrations directory.

@h3adache What do you think?

**Comment by shadowane** [comment]
The problem with having a separate file from the migrations script is that ensuring they are kept in sync is  a huge headache. The moment a developer forgets to update the outside file, things can fall apart quickly. This is especially a problem because the outside file wouldn't ever get run anywhere.

My thoughts on the limitation was that this is a totally optional way to do things and so anyone that wants to use it can use it knowing the limitation exists.

**Comment by h3adache** [comment]
The concept of migrations was to have all schema manipulations in the scripts. I don't understand why referencing an external file would be a better. An external file isn't guaranteed to be updated as you mentioned in the limitations but I would also argue that it would be less likely to be updated unless you have it as part of your project (same vcs even). You could argue that it can be but then why not just include them in standard migration script location?

In your test example. one benefit i can see is to add "common" templating (use db statements etc maybe). If that's the actual use case a pre/post script concept would be better.

Maybe it's just the wording of this ticket since I can't really understand the benefit of it. It seems to just be adding a more confusing feature.

**Comment by harawata** [comment]
Thank you, @h3adache for the input. I share your concern.

Actually, I have been thinking about the pre/post-migration hook for a while.
There is nothing concrete yet , but the basic idea is to allow users to write some script(s) that are executed before and after each migration.

In this case, for example, you could write a pre-migration script that substitutes the target string (e.g. ```@FILE```) in the migration script with the content of another file.
It fits the Migration concept and will be more versatile and flexible solution.

**Comment by shadowane** [comment]
I guess I'm not being clear, maybe.

In normal mybatis, the only changes occur through a migration script. Any time you want to update a package, a new migration script must be created, the package needs to be pasted into both the upgrade section and the undo section, and finally the upgrade section is updated. Then, further down the line if you want to update that package again, the same process needs to be followed. This means that in order to find the latest version of the package, a user needs to compare dates and ensure they find the latest one.

My change would put the package code into one file that is always the same. All updates go into that file and not anywhere else so one file is updated. This means the external file (and by external, yes I do mean in the same project just in a different folder than ./scripts) is the only one updated and the user can finally get diffs and more reasonable version control over their packages.

Does that make more sense?

**Comment by harawata** [comment]
> In normal mybatis, the only changes occur through a migration script. Any time you want to update a package, a new migration script must be created, the package needs to be pasted into both the upgrade section and the undo section, and finally the upgrade section is updated. Then, further down the line if you want to update that package again, the same process needs to be followed. 

Yes, that is how schema migration tools track changes and make it possible to bring back the database schema to a specific version.

> This means that in order to find the latest version of the package, a user needs to compare dates and ensure they find the latest one.

Right...but this is not the purpose of a schema migration tool.
Considering a normal table, migration scripts would not show you its latest definition, right? (unless you create an external file for each table in the database).

Anyway, the pre/post hook will solve your problem and other even more unique :grin: requirements once it's implemented.
It might take some time, but I'll look into it.

Thanks again for taking the time to create the PR and share your thoughts!
It's much more valuable than just tweeting around 😆

**Pull request closed without merging**
